---
title: "AE recurrent events"
output:
  pdf_document: default
---

```{r}
library(dplyr)
library(lubridate)
library(sandwich)
library(lmtest)
library(lme4)
library(coxme)
library(gtsummary)
library(gt)
library(survival)
```

```{r}
set.seed(4234)
```


```{r}
surv_df = read.csv("output/ae_survival_data_mapped.csv")
hardware_surv_df = read.csv("output/ae_survival_data_mappedhardware.csv")
software_surv_df = read.csv("output/ae_survival_data_mappedsoftware.csv")
human_surv_df = read.csv("output/ae_survival_data_mappedhuman_error.csv")
```


```{r}
# table(surv_df$panel_lead[surv_df$ae_num == 0])
table(surv_df$panel_lead)
```


```{r}
normalize_times <- function(surv_df1) {
  surv_df1$t_start_year = as.numeric(substr(surv_df1$t_start, 1, 4))
  
  day_seconds = 24 * 60 * 60 * 365
  surv_df1$t_start = as.character(surv_df1$t_start)
  surv_df1$t_end = as.character(surv_df1$t_end)
  surv_df1$t_start = as.numeric(as.POSIXct(surv_df1$t_start, format = "%Y%m%d", tz = "UTC"))/day_seconds
  surv_df1$t_start_absolute = surv_df1$t_start
  surv_df1$t_end = as.numeric(as.POSIXct(surv_df1$t_end, format = "%Y%m%d", tz = "UTC"))/day_seconds
  
  dev_num_unique = unique(surv_df1$device_num)
  for (dev_num in dev_num_unique){
    min_start = min(surv_df1$t_start[(surv_df1$device_num == dev_num)])
    surv_df1$t_start[surv_df1$device_num == dev_num] = surv_df1$t_start[surv_df1$device_num == dev_num] - min_start
    surv_df1$t_end[surv_df1$device_num == dev_num] = surv_df1$t_end[surv_df1$device_num == dev_num] - min_start
  }  
  surv_df1
}
```

```{r}
surv_df = normalize_times(surv_df)
hardware_surv_df = normalize_times(hardware_surv_df)
software_surv_df = normalize_times(software_surv_df)
human_surv_df = normalize_times(human_surv_df)
```


# DESCRIPTIVE STATISTICS

```{r}
summary_df = c(
  "number of uniq devices"=length(unique(surv_df$device_num[surv_df$predicate_num != "ROOT"])),
  "number of uniq predicates"=length(unique(surv_df$predicate_num[surv_df$predicate_num != "ROOT"])),
  "number of events"=sum(surv_df$event[surv_df$predicate_num != "ROOT"]),
  "number of first events"=sum(surv_df$event[(surv_df$ae_num == 0) & (surv_df$predicate_num != "ROOT")]),
  "number of devices with events"=length(unique(surv_df$device_num[(surv_df$ae_num > 0) & (surv_df$predicate_num != "ROOT")])),
  "number of obs"=nrow(surv_df)
)
data.frame(summary_df)
```

```{r}
colMeans(surv_df[surv_df$ae_num == 0,
  c("intended_use_and_clinical_applications",
  "operational_and_workflow_change",
  "algorithm_or_software_feature_changes",
  "hardware_changes",
  "body_part_changes",
  "human_device_team_testing",
  "has_clinical_testing")
])
```



# Ordinary cox proportional hazard model: time to FIRST adverse events
```{r}
all_ae_mdl = coxph(
  Surv(t_start, t_end, event) ~ t_start_absolute + intended_use_and_clinical_applications + 
    operational_and_workflow_change + algorithm_or_software_feature_changes + 
    hardware_changes + body_part_changes + human_device_team_testing + has_clinical_testing + predicate_has_recall* predicate_has_ae
, data = surv_df[(surv_df$ae_num == 0) & (surv_df$predicate_num!= "ROOT"),])
summary(all_ae_mdl)
```

```{r}
all_ae_mdl = coxme(
  Surv(t_start, t_end, event) ~ t_start_absolute + intended_use_and_clinical_applications + 
    operational_and_workflow_change + algorithm_or_software_feature_changes + 
    hardware_changes + body_part_changes + human_device_team_testing + has_clinical_testing + predicate_has_recall* predicate_has_ae + (1 | panel_lead)
, data = surv_df[(surv_df$ae_num == 0) & (surv_df$predicate_num!= "ROOT"),])
summary(all_ae_mdl)
```


```{r}
hardware_ae_mdl = coxph(
  Surv(t_start, t_end, event) ~ t_start_absolute + intended_use_and_clinical_applications + 
    operational_and_workflow_change + algorithm_or_software_feature_changes + 
    hardware_changes + body_part_changes + human_device_team_testing + has_clinical_testing + predicate_has_recall* predicate_has_ae,
  data = hardware_surv_df[(hardware_surv_df$ae_num == 0) & (hardware_surv_df$predicate_num!= "ROOT"),],
  robust = TRUE,
  cluster=device_num)
summary(hardware_ae_mdl)
```

```{r}
hardware_ae_mdl = coxme(
  Surv(t_start, t_end, event) ~ t_start_absolute + intended_use_and_clinical_applications + 
    operational_and_workflow_change + algorithm_or_software_feature_changes + 
    hardware_changes + body_part_changes + human_device_team_testing + has_clinical_testing + predicate_has_recall* predicate_has_ae + (1 | panel_lead)
, data = hardware_surv_df[(hardware_surv_df$ae_num == 0) & (hardware_surv_df$predicate_num!= "ROOT"),])
summary(hardware_ae_mdl)
```

```{r}
software_ae_mdl = coxph(
  Surv(t_start, t_end, event) ~ t_start_absolute + intended_use_and_clinical_applications + 
    operational_and_workflow_change + algorithm_or_software_feature_changes + 
    hardware_changes + body_part_changes + human_device_team_testing + has_clinical_testing + predicate_has_recall * predicate_has_ae,
  data = software_surv_df[(software_surv_df$ae_num == 0) & (software_surv_df$predicate_num!= "ROOT"),],
  robust = TRUE,
  cluster=device_num)
summary(software_ae_mdl)
```

```{r}
software_ae_mdl = coxme(
  Surv(t_start, t_end, event) ~ t_start_absolute + intended_use_and_clinical_applications + 
    operational_and_workflow_change + algorithm_or_software_feature_changes + 
    hardware_changes + body_part_changes + human_device_team_testing + has_clinical_testing + predicate_has_recall * predicate_has_ae + (1 | panel_lead),
  data = software_surv_df[(software_surv_df$ae_num == 0) & (software_surv_df$predicate_num!= "ROOT"),])
summary(software_ae_mdl)
```

```{r}
human_ae_mdl = coxph(
  Surv(t_start, t_end, event) ~ t_start_absolute + intended_use_and_clinical_applications + 
    operational_and_workflow_change + algorithm_or_software_feature_changes + 
    hardware_changes + body_part_changes + human_device_team_testing + has_clinical_testing + predicate_has_recall* predicate_has_ae,
  data = human_surv_df[(human_surv_df$ae_num == 0) & (human_surv_df$predicate_num!= "ROOT"),],
  robust = TRUE,
  cluster=device_num)
summary(human_ae_mdl)
```


```{r}
human_ae_mdl = coxme(
  Surv(t_start, t_end, event) ~ t_start_absolute + intended_use_and_clinical_applications + 
    operational_and_workflow_change + algorithm_or_software_feature_changes + 
    hardware_changes + body_part_changes + human_device_team_testing + has_clinical_testing + predicate_has_recall* predicate_has_ae + (1|panel_lead),
  data = human_surv_df[(human_surv_df$ae_num == 0) & (human_surv_df$predicate_num!= "ROOT"),])
summary(human_ae_mdl)
```
```{r}
tidy_coxme <- function(x, conf.level = 0.95, exponentiate = FALSE, ...) {
  print("adfasdf")
  # 1) extract fixed effects
  b   <- fixef(x)
  # 2) get variances → SEs
  se  <- sqrt(diag(vcov(x)))
  # 3) CIs
  alpha <- 1 - conf.level
  z     <- qnorm(1 - alpha/2)
  ci_lo <- b - z * se
  ci_hi <- b + z * se
  # 4) assemble
  df <- tibble(
    term      = names(b),
    variable      = names(b),
    estimate  = as.numeric(b),
    std.error = se,
    conf.low  = ci_lo,
    conf.high = ci_hi,
    p.value   = 2 * pnorm(-abs(b/se))
  )
  print(df)
  
  if (exponentiate) {
    df <- df %>%
      mutate(across(c(estimate, conf.low, conf.high), exp))
  }
  df
}
```


```{r}
library(coxme)
library(dplyr)
library(purrr)
library(tibble)
library(knitr)
library(kableExtra)
library(stats)

# 2. Extract and tidy
tidy_coxme_table <- function(mod, conf.level = 0.95) {
  b     <- fixef(mod)
  se    <- sqrt(diag(vcov(mod)))
  z     <- qnorm(1 - (1 - conf.level) / 2)
  ci_lo <- b - z * se
  ci_hi <- b + z * se
  hr    <- exp(b)
  ci_hr <- exp(cbind(ci_lo, ci_hi))
  pval  <- 2 * pnorm(-abs(b / se))

  tibble(
    Variable       = names(b),
    HR = hr,
    `95% CI` = paste0(signif(ci_hr[,1], 2), ", ", signif(ci_hr[,2], 2)),
    `p-val`      = pval
  )
}


combined_df = tidy_coxme_table(all_ae_mdl) %>%
  merge(tidy_coxme_table(hardware_ae_mdl), by = "Variable", suffix = c(" a", " b")) %>%
  merge(tidy_coxme_table(software_ae_mdl), by = "Variable", suffix = c("", " c")) %>%
  merge(tidy_coxme_table(human_ae_mdl), by = "Variable", suffix = c("", " d"))
merged_gt = combined_df %>% gt() %>%
  tab_spanner(
    label   = "All AE",
    columns = vars(ends_with(" a"))
  ) %>%
  tab_spanner(
    label   = "Hardware AE",
    columns = vars(ends_with(" b"))
  ) %>%
  tab_spanner(
    label   = "Software AE",
    columns = vars(ends_with(" c"))
  ) %>%
  tab_spanner(
    label   = "Human AE",
    columns = vars(ends_with(" d"))
  ) %>%
  fmt_number(
    columns  = matches("HR"),
    decimals = 2
  ) %>%
  fmt_number(
    columns  = matches("p-val"),
    decimals = 2
  )
merged_gt
```

```{r}
merged_gt |> gt::gtsave("output/survival_results.tex")
```

# Logistic regression sensitivity analysis


```{r}
library(splines)
run_severe_lr <- function(threshold_ae_num) {
  lr_surv_df = surv_df[(surv_df$event == 1) & (surv_df$ae_num <= threshold_ae_num),]
  print(paste("total events", sum(lr_surv_df$event)))
  print(paste("total severe events", sum(lr_surv_df$event_type %in% c("injury", "death"))))
  # lr_surv_df$predicate_has_severe_ae = pmax(lr_surv_df$predicate_has_death_ae, lr_surv_df$predicate_has_injury_ae)
  # lr_severe = glm(
  #   I(event_type %in% c("injury", "death")) ~ t_start_absolute  + intended_use_and_clinical_applications + 
  #     operational_and_workflow_change + algorithm_changes + software_feature_changes + 
  #     hardware_changes + body_part_changes + predicate_has_severe_ae * predicate_has_recall,
  #   family=binomial,
  #   data=lr_surv_df,
  #   weights = lr_surv_df$weight,
  # )
  lr_severe = glmer(
    I(event_type %in% c("injury", "death")) ~ t_start_absolute  + intended_use_and_clinical_applications + 
      operational_and_workflow_change + algorithm_or_software_feature_changes + 
      hardware_changes + body_part_changes + predicate_has_ae * predicate_has_recall + (1 | panel_lead),
    family=binomial,
    data=lr_surv_df,
    weights = lr_surv_df$weight,
  )
  lr_severe
}


```

```{r}
run_severe_lr(0)
```


```{r}
summary(run_severe_lr(5))
```


```{r}
lr_50_res <- run_severe_lr(50)
summary(lr_50_res)
# run_severe_lr(10)  |> tbl_regression(exponentiate=T)
# lr_severe_10_tbl |> as_gt() |> gt::gtsave("tab_2.tex")
```



```{r}
summary(run_severe_lr(1000))
```

